# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Publish to PypI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pypi-publish:
    name: Build and Upload
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/thankyou
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
    - name: Set Up Poetry
      uses: abatilo/actions-poetry@v2
    - name: Install Thank You
      run: poetry install --with dev
    - name: Build Thank You
      run: poetry build
    # - name: Publish package distributions to PyPI
    #   uses: pypa/gh-action-pypi-publish@release/v1
